apiVersion: v1
kind: Service
metadata:
  name: hu-sidecar
  namespace: hu
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hu-sidecar.horus
spec:
  selector:
    app: hu-sidecar
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
      protocol: TCP
  type: LoadBalancer
