apiVersion: v1
kind: Service
metadata:
  name: hu-gateway
  namespace: hu
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hu.horus
spec:
  selector:
    app: hu-gateway
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hu-sidecar
  namespace: hu
spec:
  selector:
    app: hu-sidecar
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
      protocol: TCP
  type: ClusterIP
