apiVersion: v1
kind: Service
metadata:
  name: convex-backend
  namespace: convex
spec:
  selector:
    app: convex-backend
  ports:
    - port: 3210
      targetPort: 3210
      name: api
    - port: 3211
      targetPort: 3211
      name: site
  type: ClusterIP
