apiVersion: v1
kind: Service
metadata:
  name: convex-base-backend
  namespace: convex
spec:
  selector:
    app: convex-base-backend
  ports:
    - port: 3210
      targetPort: 3210
      name: api
    - port: 3211
      targetPort: 3211
      name: site
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: convex-base-dashboard
  namespace: convex
spec:
  selector:
    app: convex-base-dashboard
  ports:
    - port: 6791
      targetPort: 6791
      name: http
  type: ClusterIP
