apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - postgres-configmap.yaml
  - pgbouncer-configmap.yaml
  - deployment.yaml
  - autoscaling.yaml
  - service.yaml
