apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: postgres
data:
  pgbouncer.ini: |
    [databases]
    * = host=postgres-service port=5432

    [pgbouncer]
    listen_addr = *
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 10
    min_pool_size = 5
    reserve_pool_size = 5
    reserve_pool_timeout = 5
    server_reset_query = DISCARD ALL
    ignore_startup_parameters = extra_float_digits
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    stats_period = 60
    admin_users = postgres
    stats_users = postgres
  userlist.txt: |
    "postgres" "md5a20e9d94f8d0d2b339bec81f1f7e4e54"
