apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - temporal-deployment.yaml
  - temporal-ui-deployment.yaml
  - temporal-admin-deployment.yaml
  - service.yaml
  - httproute.yaml
