apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: temporal
  labels:
    app: temporal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 7234
              name: grpc-frontend
            - containerPort: 7235
              name: grpc-history
            - containerPort: 7239
              name: grpc-matching
          env:
            - name: DB
              value: postgres12
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_SEEDS
              value: temporal-postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: temporal-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: temporal-postgres-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
