apiVersion: apps/v1
kind: Deployment
metadata:
  name: vela
  namespace: vela
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vela
  template:
    metadata:
      labels:
        app: vela
    spec:
      containers:
        - name: vela
          image: elevenam/vela:20251218-150206
          ports:
            - containerPort: 9191
          env:
            - name: VELA_VIDEO_WATCH_PATH
              value: /data/videos,/data/videos2
            - name: VELA_AUDIO_WATCH_PATH
              value: /data/audios,/data/audios2
            - name: VELA_STORAGE_PATH
              value: /data/streaming
            - name: VELA_DATABASE_PATH
              value: /data/db/vela.db
            - name: VELA_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: vela-secret
                  key: VELA_ADMIN_USER
            - name: VELA_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: vela-secret
                  key: VELA_ADMIN_PASS
            - name: VELA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vela-secret
                  key: VELA_JWT_SECRET
          volumeMounts:
            - name: videos
              mountPath: /data/videos
              subPath: royossai/Private/Videos
            - name: videos
              mountPath: /data/videos2
              subPath: royossai/Private/Hypno/video
            - name: videos
              mountPath: /data/audios
              subPath: royossai/Private/Vocals
            - name: videos
              mountPath: /data/audios2
              subPath: royossai/Private/Hypno/audio
            - name: database
              mountPath: /data/db
            - name: streaming
              mountPath: /data/streaming
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 9191
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9191
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: videos
          persistentVolumeClaim:
            claimName: vela-data
        - name: database
          persistentVolumeClaim:
            claimName: vela-db
        - name: streaming
          persistentVolumeClaim:
            claimName: vela-streaming
        - name: tmp
          emptyDir: {}
