apiVersion: v1
kind: Service
metadata:
  name: dia-service
  namespace: dia
spec:
  selector:
    app: dia
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8003
      targetPort: 8003
