apiVersion: v1
kind: Service
metadata:
  name: speaches-service
  namespace: speaches
spec:
  selector:
    app: speaches
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
