apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flow
resources:
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
