apiVersion: v1
kind: Service
metadata:
  name: flow-service
  namespace: flow
spec:
  selector:
    app: flow
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9192
      targetPort: 9192
