apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - namespace.yaml
  - github-oauth-secret.yaml
  - pull-secret.yaml
  - config-template.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml