apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - importer-deployment.yaml
  - service.yaml
  - httproute.yaml
