apiVersion: v1
kind: Service
metadata:
  name: firefly-service
  namespace: firefly
spec:
  selector:
    app: firefly
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-importer-service
  namespace: firefly
spec:
  selector:
    app: firefly-importer
  ports:
    - name: http
      port: 80
      targetPort: 8080
