apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  namespace: coturn
data:
  turnserver.conf: |
    listening-port=3478
    tls-listening-port=5349
    listening-ip=0.0.0.0
    relay-ip=0.0.0.0
    min-port=49152
    max-port=49252
    fingerprint
    lt-cred-mech
    realm=turn.horus
    log-file=stdout
    verbose
    no-cli
    allowed-peer-ip=10.0.0.0-10.255.255.255
    allowed-peer-ip=172.16.0.0-172.31.255.255
    allowed-peer-ip=192.168.0.0-192.168.255.255
