apiVersion: v1
kind: Service
metadata:
  name: launchpad
  namespace: launchpad
spec:
  selector:
    app: launchpad
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
