apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config
  namespace: zitadel
data:
  config.yaml: |
    Port: 8080
    ExternalDomain: auth.maix.ovh
    ExternalPort: 443
    ExternalSecure: true
