apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-deployment
  namespace: radarr
  labels:
    app: radarr-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: radarr-deployment
  template:
    metadata:
      name: radarr-deployment
      labels:
        app: radarr-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7878
              name: radarr
              protocol: TCP
          env:
            - name: PUID
              value: "1005"
            - name: PGID
              value: "1005"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-media
              mountPath: /media
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-data
        - name: radarr-media
          persistentVolumeClaim:
            claimName: radarr-media
