apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qdrant
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httpRoute.yaml
  - backup-cronjob.yaml