apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
  namespace: sonarr
  labels:
    app: sonarr-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: sonarr-deployment
  template:
    metadata:
      name: sonarr-deployment
      labels:
        app: sonarr-deployment
    spec:
      restartPolicy: Always
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latext
          imagePullPolicy: Always
          ports:
            - containerPort: 8989
              name: sonarr
              protocol: TCP
          env:
            - name: PUID
              value: "1005"
            - name: PGID
              value: "1005"
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-media
              mountPath: /media
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-data
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-data
        - name: sonarr-media
          persistentVolumeClaim:
            claimName: sonarr-media
