apiVersion: v1
kind: ConfigMap
metadata:
  name: pad-config
  namespace: pad
  labels:
    app: pad
data:
  PORT: "8080"
  BASE_URL: "https://blog.theossaibrothers.com"
  DATABASE_PATH: "/app/data/pad-cms.db"
  UPLOAD_PATH: "/app/data/uploads"
  ENVIRONMENT: "production"
