apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - b2-backup-secret.yaml
  - deployment.yaml
  - service.yaml
  - httpRoute.yaml
  - b2-backup-cronjob.yaml

