apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: buildkit
data:
  buildkitd.toml: |
    [registry."zot.zot.svc.cluster.local:5000"]
      http = true
      insecure = true

    [registry."zot.maix.ovh"]
      mirrors = ["zot.zot.svc.cluster.local:5000"]

    [worker.oci]
      gc = true
      gckeepbytes = 42949672960
