apiVersion: v1
kind: Service
metadata:
  name: buildkit-service
  namespace: buildkit
  annotations:
    external-dns.alpha.kubernetes.io/hostname: buildkit.horus
spec:
  type: LoadBalancer
  selector:
    app: buildkit
  ports:
    - port: 1234
      targetPort: 1234
      protocol: TCP
